### PR TITLE
Update test due (partially) to updated `stormevents`

### PR DESCRIPTION
**Pull request by SorooshMani-NOAA**

### CODE REVIEW

**Comment by SorooshMani-NOAA** [comment]
@WPringle I have two commits for this PR. One is just field width update due to `stormevents` (as expected), but the other one is something I was not expecting and I'm not sure how/when the failure started showing up. Basically the result of perturbation is a little different, can you please inspect https://github.com/noaa-ocs-modeling/EnsemblePerturbation/pull/94/commits/307074281ec76a06583180dfe20f4854dbae03d1 and see if you can find anything suspicious to fix before merging updated test references?

Note that this PR is based on `main` branch, and it does **not** have any of your updates for GAHM.

**Comment by WPringle** [comment]
@SorooshMani-NOAA For what reason did the json change? I don't see any change in the test code. But `random` suggests that those values would be randomly chosen and so would differ with each call. Not sure why we would have random in the tests.

**Comment by WPringle** [comment]
@SorooshMani-NOAA OK, I see I think that's not right to use random in the test suite. Need to change to use the `korobov` sequence or something.

**Review by WPringle — CHANGES_REQUESTED** [review]
[EnsemblePerturbation/tests/test_track_ensemble.py](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/blob/e7d9ec735b68249e69d01051a58b84838e67f6b8/tests/test_track_ensemble.py#L83-L104) needs changing to sample using repeatable technique instead of `random`. Or we can seed the randomness...

**Comment by SorooshMani-NOAA** [comment]
@WPringle you're right. The test has not changed since last year. I think since the test is done based on pseudorandomness and not real randomness, the results remained the same, but now for some reason it changed. Do you have any suggestion for updating the results or the test? Should we just go through with this updated ref for now?

**Comment by WPringle** [comment]
@SorooshMani-NOAA That's strange how it never changed.. the random method should be properly random unless it is seeded using the same value.

**Comment by SorooshMani-NOAA** [comment]
@WPringle I just realized that that specific test actually never checks the resulting files against the reference files, so even if it changes, it won't  complain! The reason I captured the changes was that I copied all update files from the output directory to reference directory after running the test.

So basically the test is: "_Is this function `perturb_tracks` running without errors?_" Given that, do you think it is OK to leave it as such for now or do you think it'd be better if we use korobov sequence instead of random and check the resulting files against the refs?

**Comment by WPringle** [comment]
@SorooshMani-NOAA I think it's ok then to leave it and just to check it's working. But we don't need reference files then I guess. Just that the files and their filenames are output correctly when the test is run.

**Pull request merged**
