### PR TITLE
Allowing for downloading real-time cyclone forecasts/best-tracks

### PR DESCRIPTION
**Pull request by WPringle**
Introducing `mode` option for ATCF to signify `historical` (default) or `real-time` storm

One problem for testing is that we need to know the storm name and initialization time. Do you have any ideas how to ping this information to get latest a-deck file in ftp://ftp.nhc.noaa.gov/atcf/aid_public/, and b-deck in ftp://ftp.nhc.noaa.gov/atcf/btk/?

### CODE REVIEW

**Comment by zacharyburnettNOAA** [comment]
> One problem for testing is that we need to know the storm name and initialization time. Do you have any ideas how to ping this information to get latest a-deck file in ftp://ftp.nhc.noaa.gov/atcf/aid_public/, and b-deck in ftp://ftp.nhc.noaa.gov/atcf/btk/?

looks like we can use ftplib and `ftp.dir()` to list files
https://www.thepythoncode.com/article/list-files-and-directories-in-ftp-server-in-python

**Comment by zacharyburnettNOAA** [comment]
https://github.com/noaa-ocs-modeling/EnsemblePerturbation/blob/c610faf08c243075cc3d7a303a201da746098ec6/ensembleperturbation/tropicalcyclone/atcf.py#L873-L889

**Comment by WPringle** [comment]
Hey thanks @zacharyburnettNOAA  for your help on the ftp! 
So I see the test is only trying to test the Florence best track now?

**Comment by zacharyburnettNOAA** [comment]
> Hey thanks @zacharyburnettNOAA for your help on the ftp!
> So I see the test is only trying to test the Florence best track now?

yeah that was my fault, I commented something out to debug

fixed in f0c8f8e2f86c9b0285ffa2eeba7bb0e520a03577

**Pull request merged**
