### PR TITLE
Disable isotach perturbation is GAHM RMW perturbation is not selected

### PR DESCRIPTION
**Pull request by SorooshMani-NOAA**
As per https://github.com/noaa-ocs-modeling/SurgeTeamCoordination/issues/615

### CODE REVIEW

**Review by WPringle — APPROVED** [review]
Thanks for the addition and coding layout changes! 
It looks like the other test results are unchanged, so it must be working as expected.

**Comment by WPringle** [comment]
To be clear, the use case is:
```python
no isotach adjustment:
features=None
 or 
features=PerturberFeatures.NONE

with isotach adjustment [default]
features=PerturberFeatures.ISOTACH_ADJUSTMENT
```

**Comment by SorooshMani-NOAA** [comment]
@WPringle yes that's what I had in mind for how to use it.

**Comment by SorooshMani-NOAA** [comment]
Given https://github.com/noaa-ocs-modeling/SurgeTeamCoordination/issues/618#issuecomment-2397760722, do you want me to wait for your changes before merging?

**Comment by WPringle** [comment]
@SorooshMani-NOAA No, I think this is fine to merge, and then can make a different PR with that change..

**Pull request merged**
