### PR TITLE
Feature/rmax psurgev29

### PR DESCRIPTION
**Pull request by WPringle**
saeed-moghimi-noaa/Next-generation-psurge-tasks#28

### CODE REVIEW

**Comment by WPringle** [comment]
Florence2018_OFCL_advisory_RMWPersistent_perturbations
Florence2018_OFCL_advisory_RMWGaussian_perturbations

**Comment by WPringle** [comment]
Will wait for merge of oceanmodeling/StormEvents/pull/96 to add new StormEvents requirement in `pyproject.toml`

**Comment by WPringle** [comment]
> @WPringle can you please merge `noaa-ocs-modeling/EnsemblePerturbation:feature/rmax_Psurgev29` to your fork's branch and see if the tests go through. I had to revert the `stormevents` related changes because `stormevents` [speed fix](https://github.com/oceanmodeling/StormEvents/pull/104) is not yet merged. We'll add them again later

Just to clarify, merge the main fork into my fork because of some changes made in made version?

**Comment by SorooshMani-NOAA** [comment]
@WPringle I started looking into the changes in ensembleperturbations today. I rebased your branch and created a new PR (#154) can you please check and see if everything looks good there and if so I can go ahead and merge that to main

**Pull request closed without merging**
