### PR TITLE
Feature: Best-track hindcast perturbation and modifications for GAHM model

### PR DESCRIPTION
**Pull request by WPringle**
This PR implements perturbations for best-track hindcast by using the 0-hr historical forecast errors across the whole best-track. This is the most straightforward way I could think of to maintain consistency with the forecast implementation. 

For Rmax the 0-hr errors were 0 so I changed them by linear extrapolation using the 12-hr and 24-hr values. This should have a minimal effect on the forecast implementation by slightly changing Rmax at the first time step.

For application to the Generalized Asymmetric Holland Model (GAHM), I added the lines to modify the isotach radii across the four quadrants. These radii are modified in the exact same way the Rmax is modified and the modification is controlled by the same parameter. i.e., The RadiustoMaximumWinds variable controls Rmax and  the isotach radii all in one. That way we keep the four variables of cross track, along track, intensity (Vmax and Pc), and size (Rmax, isotach radii).

Some other changes got in from some things I did before for improvements to plotting.

### CODE REVIEW

**Comment by WPringle** [comment]
Example of best-track 19 member ensemble of Florence using the plotter:
Florence2018_hindcast_perturbations

**Comment by SorooshMani-NOAA** [comment]
@WPringle before updating test references here (in `ensembleperturbation` repo), I'd like to finalize the field-width adjustment in `stormevents` at https://github.com/oceanmodeling/StormEvents/pull/73, since unfortunately the test results in this repo (as well as in `coupledmodeldriver`) are dependent on results of `stormevents`. After that let's get back to merging this.

**Comment by WPringle** [comment]
@SorooshMani-NOAA Yep, that sounds good. The StormEvent#73 was merged

**Comment by SorooshMani-NOAA** [comment]
@WPringle thanks. I'm going down the chain, `adcircpy` -> `coupledmodeldriver` -> `ensembleperturbation` and fixing the tests and releasing to get to this repo. We need to have a better testing strategy so that a small width change like [this](https://github.com/oceanmodeling/StormEvents/pull/73) doesn't require all of the dependent repos to updated their tests!

**Comment by WPringle** [comment]
@SorooshMani-NOAA That's true..!

**Comment by SorooshMani-NOAA** [comment]
I'm going to create a separate branch that updates the test based on updated stormevents, then I'll merge it to main and you can then merge main back to your branch so that if there are any new test failures, we know it's **not** due to `stormevents`. I think that's the cleanest way to proceed.

**Comment by SorooshMani-NOAA** [comment]
@WPringle I updated the tests for the `stormevents` dependency (#94). Please merge `main` into your branch and rerun the tests to see if anything still fails. If so, then it should be a failure due to new changes and not due to changes in `stormevents`. Thanks!

**Comment by WPringle** [comment]
@SorooshMani-NOAA Can you please update StormEvents to version 2.1.4? I thought was supposed to be automated but it hasn't updated.

**Comment by SorooshMani-NOAA** [comment]
> @SorooshMani-NOAA Can you please update StormEvents to version 2.1.4? I thought was supposed to be automated but it hasn't updated.

@WPringle sorry I don't know how I missed this! I think the issue might be the "cached" dependencies. Since anyway we really have to have `stormevents >= 2.1.4` we can set this in the requirement file. Since this should go in with the rest of your changes, can you please add that in here (that also avoids another separate pull request):
https://github.com/noaa-ocs-modeling/EnsemblePerturbation/blob/78c4931f72cd661c07997fe541459ae1e00cddbc/pyproject.toml#L47

and update the version to be `'>=2.1.4'` instead? Thanks!

Please let me know if there are still issues after doing that.

**Comment by WPringle** [comment]
> > @SorooshMani-NOAA Can you please update StormEvents to version 2.1.4? I thought was supposed to be automated but it hasn't updated.
> 
> @WPringle sorry I don't know how I missed this! I think the issue might be the "cached" dependencies. Since anyway we really have to have `stormevents >= 2.1.4` we can set this in the requirement file. Since this should go in with the rest of your changes, can you please add that in here (that also avoids another separate pull request):
> 
> https://github.com/noaa-ocs-modeling/EnsemblePerturbation/blob/78c4931f72cd661c07997fe541459ae1e00cddbc/pyproject.toml#L47
> 
> and update the version to be `'>=2.1.4'` instead? Thanks!
> 
> Please let me know if there are still issues after doing that.

@SorooshMani-NOAA Yep I'm doing that on my end to change to '>=2.1.4' but this version cannot be found in `StormEvents`. Only up to version 2.1.3 exists although I merged in a PR after this version and should've updated to 2.1.4 I thought.

**Comment by SorooshMani-NOAA** [comment]
Oh I see what you're saying! I just created the `2.1.4` release on StormEvents repo. Give it a minute to be uploaded to PyPI.

**Comment by WPringle** [comment]
@SorooshMani-NOAA The tests seem to run on my local side, can you try also on your end?

**Comment by SorooshMani-NOAA** [comment]
@WPringle I seem to be getting the same error:
```
========================================= short test summary info =========================================
FAILED tests/test_bestrack_ensemble.py::test_multivariate_besttrack_ensemble - FileNotFoundError: [Errno 2] No such file or directory: '/home/smani/workarea/sandbox/ensembleperturba...
================================ 1 failed, 6 passed, 33 warnings in 30.70s ================================
```

**Comment by WPringle** [comment]
@SorooshMani-NOAA Thanks yes, I found there were extra unneeded reference files. Previously, the output file name contained `perturbation` and then it got changed to use the `sample_rule` instead, which I think was one reason why there were added files. I changed it back so that `sample_rule` is used in the filename only when actually sampling from the distribution.

**Comment by SorooshMani-NOAA** [comment]
@WPringle do these changes mean that the analysis works for both symmetric as well as GAHM? or does it just now work for GAHM only?

**Comment by SorooshMani-NOAA** [comment]
@WPringle do these changes mean that the analysis works for both symmetric as well as GAHM? or does it just now work for GAHM only?

**Comment by WPringle** [comment]
@SorooshMani-NOAA These changes work for both at the same time. It is just a matter of choosing what wind model to use when running simulation. Only difference is that we also adjust the quadrant radii (r34, r50, r64-kt) in this but these just go unused for the symmetric model.

**Pull request merged**
