### PR TITLE
adding example that can be used to assemble ensemble inputs and outputs 

### PR DESCRIPTION
**Pull request by WPringle**
assembles set of ensemble runs into a single dataframe (one for input, one for output), and saves as HDF5 file

### CODE REVIEW

**Comment by zacharyburnettNOAA** [comment]
@WPringle should this run on an adcirc run with `vortex.json` as the perturbation?

**Comment by WPringle** [comment]
> @WPringle should this run on an adcirc run with `vortex.json` as the perturbation?

I put in `vortex.json` just as an example here but I don't think that's necessary (see Orion `share/working/william/Florence_Perturbation_Test`). 
We could just search for any json file in the folder as long as that is the only one.

**Comment by zacharyburnettNOAA** [comment]
> What is the normal file name format that will be generated for this json?

It should look like this:
```
vortex_4_variable_perturbation_1.22
vortex_4_variable_perturbation_1.json
vortex_4_variable_perturbation_2.22
vortex_4_variable_perturbation_2.json
vortex_4_variable_perturbation_3.22
vortex_4_variable_perturbation_3.json
```

**Comment by WPringle** [comment]
yeah ok so we could just change it to `vortex*.json`

**Comment by WPringle** [comment]
I think is good if you are happy with it.

**Pull request merged**
