### PR TITLE
Fix cross track point perturbation

### LINKED ISSUE #118: Perturbation bug on turn to NE
See https://github.com/saeed-moghimi-noaa/Next-generation-psurge-tasks/issues/6#issuecomment-1834039503

### PR DESCRIPTION
**Pull request by SorooshMani-NOAA**
Fixes #118

### CODE REVIEW

**Comment by SorooshMani-NOAA** [comment]
@WPringle I think the failed tests are due to wrong references. I'll do more testing on all the 3 storms from NHC, but can you check if you see anything wrong with the changes I made?

**Comment by WPringle** [comment]
@SorooshMani-NOAA Thanks for fix! Although it's strange since `alpha` already looks like it should be positive always and reason for not needing abs() value.

**Comment by WPringle** [comment]
> > Although it's strange since alpha already looks like it should be positive
> 
> @WPringle I actually realized that later, but just wanted to be extra sure, the main fix was related to how 1 dim arrays where being incorrectly `mean`ed or `diff`ed

oh right, gotcha. think everything  looks good

**Review by WPringle — APPROVED** [review]
if things are fixed without adding abs() around alpha then maybe don't make this change as it makes you think this is the bug but it's actually the other lines..

**Pull request merged**
