### PR TITLE
Feature/time series

### PR DESCRIPTION
**Pull request by FariborzDaneshvar-NOAA**
Added optional timeslot input (default=1) to `compute_surrogate_percentiles()` and `compute_surrogate_probability_field()` functions to avoid MemoryError when calculating `poly1 = poly(*Z)`

### CODE REVIEW

**Comment by SorooshMani-NOAA** [comment]
@FariborzDaneshvar-NOAA just for the sake of future reference, can you please include some of the multi step plots, etc. that was generated using this approach? I mean can you please attach snapshots as a PR comment?

**Comment by FariborzDaneshvar-NOAA** [comment]
> @FariborzDaneshvar-NOAA just for the sake of future reference, can you please include some of the multi step plots, etc. that was generated using this approach? I mean can you please attach snapshots as a PR comment?

This update doesn't change plots. It only passes surrogate_model in chunks to `Poly1(*Z)` in [surrogate.py](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/blob/feature/time_series/ensembleperturbation/uncertainty_quantification/surrogate.py).

This is what we had before for percentiles:

```python
        surrogate_percentiles = compute_surrogate_percentiles(
            poly=surrogate_model,
            q=percentiles,
            dist=distribution,
            convert_from_log_scale=convert_from_log_scale,
        )
```

But with this new update, it will use multiple chunks of surrogate_model (default number of timeslots is 1):

```python 
    # use chunks of surrogate model (for each timeslot) to calculate percentiles
    surr_chunk_length = int(surrogate_model.shape[0] / timeslots)

    for timestep in range(timeslots):
        surrogate_percentiles_chunk = compute_surrogate_percentiles(
            poly=surrogate_model[
                (timestep * surr_chunk_length) : ((timestep + 1) * surr_chunk_length)
            ],
            q=percentiles,
            dist=distribution,
            convert_from_log_scale=convert_from_log_scale,
        )
        if timestep == 0:
            surrogate_percentiles = surrogate_percentiles_chunk
        else:
            surrogate_percentiles = numpy.concatenate(
                (surrogate_percentiles, surrogate_percentiles_chunk), axis=1
            )
```

**Comment by SorooshMani-NOAA** [comment]
Thanks @FariborzDaneshvar-NOAA can you verify that we get the same plots as before if you run this code on the maxelev data?

**Comment by FariborzDaneshvar-NOAA** [comment]
Here are the percentiles and probability plots of a given surrogate_model, from the old code ([main](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/tree/main) branch) and the new code ([feature/time_series](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/tree/feature/time_series) branch) with timeslot variable:

| [main branch](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/tree/main) | [feature/time_series](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/tree/feature/time_series) branch (default `timeslot=1`) | [feature/time_series branch](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/tree/feature/time_series) (user-defined `timeslot=1`) | 
| --- | --- | --- |
| 001_old_code_percentiles_70 | 002_new_code_default_percentiles_70 | 002_new_code_user-defined_percentiles_70 |
| 000_old_code_probability_exceeding_4_ft | 001_new_code_default_probability_exceeding_4_ft | probability_exceeding_4_ft |

Three plots are exactly the same, confirming that the newly added variable (`timeslot`) doesn't change the outputs/plots.

**Comment by SorooshMani-NOAA** [comment]
Thank you, I'll go ahead with the merge then!

**Pull request merged**
